version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - .:/src
      - /src/node_modules
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"